name: llama
run-name: ${{ github.actor }} is running tests for ${{ github.workflow }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout x
        uses: actions/checkout@v4
      - uses: ./.github/actions/base
        with:
          checkout_y: true
          require_gcc: true
      - name: Run ${{ github.workflow }} Test
        run: make -C ${{ github.workspace }}/ clean test
      - name: Run ${{ github.workflow }} Release
        run: make -C ${{ github.workspace }}/ clean release
